const hangmanWords = [
  "abandon",
  "ability",
  "absence",
  "academy",
  "accident",
  "account",
  "accuracy",
  "achieve",
  "activity",
  "addition",
  "address",
  "adjust",
  "advance",
  "advice",
  "affect",
  "afford",
  "against",
  "aircraft",
  "airport",
  "alcohol",
  "allegation",
  "alliance",
  "allowance",
  "amazing",
  "ambition",
  "analysis",
  "ancestor",
  "ancient",
  "announce",
  "annual",
  "anxiety",
  "apology",
  "apparent",
  "appeal",
  "appoint",
  "approach",
  "approval",
  "argument",
  "arrange",
  "arrival",
  "article",
  "artistic",
  "ashamed",
  "aspect",
  "assembly",
  "assess",
  "assign",
  "assist",
  "assume",
  "athlete",
  "attempt",
  "attract",
  "auction",
  "average",
  "backbone",
  "balance",
  "bargain",
  "barrier",
  "battery",
  "behavior",
  "benefit",
  "besides",
  "between",
  "beyond",
  "billion",
  "biology",
  "birthday",
  "blanket",
  "blessing",
  "boundary",
  "bravery",
  "breathe",
  "briefly",
  "brother",
  "builder",
  "burden",
  "butter",
  "cabinet",
  "calculate",
  "campaign",
  "capacity",
  "capital",
  "capture",
  "careful",
  "carrier",
  "category",
  "caution",
  "celebrate",
  "ceremony",
  "chairman",
  "champion",
  "channel",
  "chapter",
  "charity",
  "chemical",
  "chicken",
  "childhood",
  "circuit",
  "citizen",
  "civilian",
  "clarify",
  "classic",
  "climate",
  "closely",
  "clothing",
  "collapse",
  "collect",
  "college",
  "combine",
  "comfort",
  "command",
  "comment",
  "commerce",
  "commission",
  "committee",
  "companion",
  "compare",
  "compete",
  "complain",
  "complete",
  "complex",
  "compose",
  "concept",
  "concern",
  "concert",
  "conclude",
  "condition",
  "conduct",
  "conflict",
  "confuse",
  "connect",
  "conscious",
  "consider",
  "consist",
  "constant",
  "construct",
  "consult",
  "contact",
  "contain",
  "contest",
  "context",
  "control",
  "convert",
  "convince",
  "cooking",
  "correct",
  "council",
  "counsel",
  "counter",
  "country",
  "courage",
  "coverage",
  "crucial",
  "culture",
  "curious",
  "current",
  "customer",
  "damage",
  "danger",
  "darkness",
  "database",
  "daughter",
  "daylight",
  "deadline",
  "decade",
  "declare",
  "decline",
  "decorate",
  "decrease",
  "dedicate",
  "defeat",
  "defense",
  "deficit",
  "deliver",
  "demand",
  "density",
  "departure",
  "depend",
  "deposit",
  "describe",
  "deserve",
  "desire",
  "destroy",
  "develop",
  "device",
  "devote",
  "diagram",
  "diamond",
  "digital",
  "dignity",
  "disaster",
  "disclose",
  "discount",
  "discover",
  "discuss",
  "disease",
  "dismiss",
  "display",
  "distance",
  "distinct",
  "district",
  "diverse",
  "divorce",
  "doctrine",
  "document",
  "domestic",
  "dominant",
  "dominate",
  "donation",
  "double",
  "drama",
  "drawing",
  "dream",
  "dressing",
  "driving",
  "dynamic",
  "eager",
  "earnings",
  "economy",
  "edition",
  "educate",
  "effect",
  "effort",
  "elderly",
  "election",
  "electric",
  "elegant",
  "element",
  "elevator",
  "embrace",
  "emerge",
  "emotion",
  "emphasis",
  "employee",
  "employer",
  "enable",
  "encounter",
  "engage",
  "engine",
  "enhance",
  "enjoy",
  "enormous",
  "enough",
  "enquiry",
  "ensure",
  "entire",
  "entrance",
  "envelope",
  "episode",
  "equation",
  "equip",
  "equity",
  "escape",
  "especially",
  "essay",
  "essential",
  "establish",
  "estimate",
  "evaluate",
  "eventually",
  "evidence",
  "evolution",
  "examine",
  "example",
  "exceed",
  "excellent",
  "exchange",
  "exciting",
  "execute",
  "exercise",
  "exhibit",
  "existence",
  "expansion",
  "expect",
  "expense",
  "experience",
  "expert",
  "explain",
  "explode",
  "explore",
  "express",
  "extend",
  "external",
  "extreme",
  "facility",
  "failure",
  "familiar",
  "fantasy",
  "fashion",
  "feature",
  "federal",
  "feedback",
  "festival",
  "fiction",
  "finance",
  "finding",
  "fitness",
  "flavor",
  "flexible",
  "focus",
  "follow",
  "football",
  "forecast",
  "foreign",
  "forever",
  "forgive",
  "formal",
  "fortune",
  "forward",
  "founder",
  "freedom",
  "frequent",
  "friendly",
  "frustrate",
  "function",
  "fundamental",
  "further",
  "gallery",
  "garbage",
  "garden",
  "gather",
  "general",
  "generate",
  "generous",
  "genetic",
  "genuine",
  "gesture",
  "glance",
  "global",
  "glorious",
  "govern",
  "graduate",
  "grateful",
  "gravity",
  "greatest",
  "grocery",
  "guarantee",
  "guidance",
  "guilty",
  "habitat",
  "happiness",
  "hardware",
  "harvest",
  "heading",
  "healthy",
  "hearing",
  "heavily",
  "helicopter",
  "heritage",
  "hesitate",
  "highlight",
  "historical",
  "holiday",
  "honesty",
  "horizon",
  "horror",
  "hospital",
  "hostile",
  "household",
  "humanity",
  "humble",
  "humor",
  "hunger",
  "hunting",
  "husband",
  "hybrid",
  "identify",
  "identity",
  "ignore",
  "illegal",
  "illness",
  "illustrate",
  "imagine",
  "immediate",
  "immigrant",
  "impact",
  "implement",
  "important",
  "impose",
  "impress",
  "improve",
  "include",
  "increase",
  "indicate",
  "individual",
  "industry",
  "influence",
  "inform",
  "initial",
  "innocent",
  "inquiry",
  "insight",
  "inspire",
  "install",
  "instance",
  "institute",
  "instruct",
  "insurance",
  "integrate",
  "intense",
  "interest",
  "internal",
  "interpret",
  "interval",
  "interview",
  "introduce",
  "invasion",
  "invest",
  "involve",
  "isolate",
  "issue",
  "itemize",
  "jacket",
  "jealous",
  "journal",
  "journey",
  "justice",
  "justify",
  "juvenile",
  "keyboard",
  "kingdom",
  "kitchen",
  "knowledge",
  "landscape",
  "language",
  "laughter",
  "lawyer",
  "leader",
  "learning",
  "lecture",
  "legalize",
  "leisure",
  "liberty",
  "library",
  "license",
  "lifelong",
  "lightning",
  "literary",
  "location",
  "logical",
  "loyalty",
  "lumber",
  "lunar",
];

let guessingWord;
let wordLength;
let misses = 0;
let correctGuesses = 0;
let winCheck;

chooseWord();

function chooseWord() {
  guessingWord =
    hangmanWords[Math.floor(Math.random() * hangmanWords.length)].toLowerCase();
  displayWord();
}

function displayWord() {
  wordLength = guessingWord.length;
  const wordElement = document.getElementById("word");
  wordElement.innerHTML = "";
  for (let i = 0; i < wordLength; i++) {
    wordElement.innerHTML += `<td id="${i}">__</td>`;
  }
}

const buttons = document.getElementsByClassName("btn");
for (let button of buttons) {
  button.addEventListener("click", function () {
    if (button.disabled) return; // Check if the button has been pressed before

    button.disabled = true; // Disable the button after it's pressed

    if (guessingWord.includes(button.innerHTML)) {
      button.style.background = "green";
      for (let y = 0; y < guessingWord.length; y++) {
        if (guessingWord[y] === button.innerHTML) {
          document.getElementById(y).innerHTML = button.innerHTML;
          checkIfWon();
        }
      }
    } else {
      button.style.textDecoration = "line-through";
      button.style.background = "darkgray";
      misses++;
      if (misses === 12) {
        document.body.style.background = "red";
        disableAllButtons();
      }
    }
  });
}

function checkIfWon() {
  winCheck = "";
  for (let z = 0; z < guessingWord.length; z++) {
    winCheck += document.getElementById(z).innerHTML;
  }
  if (winCheck === guessingWord) {
    document.body.style.background = "green";
    disableAllButtons();
  }
}

document.getElementById("submit").addEventListener("click", function () {
  const input = document.getElementById("input").value.toLowerCase();
  if (input === guessingWord) {
    document.body.style.background = "green";
    document.getElementById("word").innerHTML = "Word: " + guessingWord;
    disableAllButtons();
  } else {
    misses += 2;
    document.getElementById("input").value = "";
    if (misses >= 12) {
      document.body.style.background = "red";
      disableAllButtons();
    }
  }
});

function disableAllButtons() {
  for (let button of buttons) {
    button.disabled = true;
  }
}
