
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `post` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model post
 * 
 */
export type postModel = runtime.Types.Result.DefaultSelection<Prisma.$postPayload>

export type AggregatePost = {
  _count: PostCountAggregateOutputType | null
  _min: PostMinAggregateOutputType | null
  _max: PostMaxAggregateOutputType | null
}

export type PostMinAggregateOutputType = {
  id: string | null
  title: string | null
  content: string | null
  userId: string | null
}

export type PostMaxAggregateOutputType = {
  id: string | null
  title: string | null
  content: string | null
  userId: string | null
}

export type PostCountAggregateOutputType = {
  id: number
  title: number
  content: number
  userId: number
  _all: number
}


export type PostMinAggregateInputType = {
  id?: true
  title?: true
  content?: true
  userId?: true
}

export type PostMaxAggregateInputType = {
  id?: true
  title?: true
  content?: true
  userId?: true
}

export type PostCountAggregateInputType = {
  id?: true
  title?: true
  content?: true
  userId?: true
  _all?: true
}

export type PostAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which post to aggregate.
   */
  where?: Prisma.postWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of posts to fetch.
   */
  orderBy?: Prisma.postOrderByWithRelationInput | Prisma.postOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.postWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` posts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` posts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned posts
  **/
  _count?: true | PostCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PostMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PostMaxAggregateInputType
}

export type GetPostAggregateType<T extends PostAggregateArgs> = {
      [P in keyof T & keyof AggregatePost]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePost[P]>
    : Prisma.GetScalarType<T[P], AggregatePost[P]>
}




export type postGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.postWhereInput
  orderBy?: Prisma.postOrderByWithAggregationInput | Prisma.postOrderByWithAggregationInput[]
  by: Prisma.PostScalarFieldEnum[] | Prisma.PostScalarFieldEnum
  having?: Prisma.postScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PostCountAggregateInputType | true
  _min?: PostMinAggregateInputType
  _max?: PostMaxAggregateInputType
}

export type PostGroupByOutputType = {
  id: string
  title: string
  content: string
  userId: string
  _count: PostCountAggregateOutputType | null
  _min: PostMinAggregateOutputType | null
  _max: PostMaxAggregateOutputType | null
}

type GetPostGroupByPayload<T extends postGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PostGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PostGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PostGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PostGroupByOutputType[P]>
      }
    >
  >



export type postWhereInput = {
  AND?: Prisma.postWhereInput | Prisma.postWhereInput[]
  OR?: Prisma.postWhereInput[]
  NOT?: Prisma.postWhereInput | Prisma.postWhereInput[]
  id?: Prisma.StringFilter<"post"> | string
  title?: Prisma.StringFilter<"post"> | string
  content?: Prisma.StringFilter<"post"> | string
  userId?: Prisma.StringFilter<"post"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.userWhereInput>
}

export type postOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  user?: Prisma.userOrderByWithRelationInput
}

export type postWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.postWhereInput | Prisma.postWhereInput[]
  OR?: Prisma.postWhereInput[]
  NOT?: Prisma.postWhereInput | Prisma.postWhereInput[]
  title?: Prisma.StringFilter<"post"> | string
  content?: Prisma.StringFilter<"post"> | string
  userId?: Prisma.StringFilter<"post"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.userWhereInput>
}, "id">

export type postOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  _count?: Prisma.postCountOrderByAggregateInput
  _max?: Prisma.postMaxOrderByAggregateInput
  _min?: Prisma.postMinOrderByAggregateInput
}

export type postScalarWhereWithAggregatesInput = {
  AND?: Prisma.postScalarWhereWithAggregatesInput | Prisma.postScalarWhereWithAggregatesInput[]
  OR?: Prisma.postScalarWhereWithAggregatesInput[]
  NOT?: Prisma.postScalarWhereWithAggregatesInput | Prisma.postScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"post"> | string
  title?: Prisma.StringWithAggregatesFilter<"post"> | string
  content?: Prisma.StringWithAggregatesFilter<"post"> | string
  userId?: Prisma.StringWithAggregatesFilter<"post"> | string
}

export type postCreateInput = {
  id?: string
  title: string
  content: string
  user: Prisma.userCreateNestedOneWithoutPostsInput
}

export type postUncheckedCreateInput = {
  id?: string
  title: string
  content: string
  userId: string
}

export type postUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  user?: Prisma.userUpdateOneRequiredWithoutPostsNestedInput
}

export type postUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type postCreateManyInput = {
  id?: string
  title: string
  content: string
  userId: string
}

export type postUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
}

export type postUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PostListRelationFilter = {
  every?: Prisma.postWhereInput
  some?: Prisma.postWhereInput
  none?: Prisma.postWhereInput
}

export type postOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type postCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type postMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type postMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type postCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.postCreateWithoutUserInput, Prisma.postUncheckedCreateWithoutUserInput> | Prisma.postCreateWithoutUserInput[] | Prisma.postUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.postCreateOrConnectWithoutUserInput | Prisma.postCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.postCreateManyUserInputEnvelope
  connect?: Prisma.postWhereUniqueInput | Prisma.postWhereUniqueInput[]
}

export type postUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.postCreateWithoutUserInput, Prisma.postUncheckedCreateWithoutUserInput> | Prisma.postCreateWithoutUserInput[] | Prisma.postUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.postCreateOrConnectWithoutUserInput | Prisma.postCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.postCreateManyUserInputEnvelope
  connect?: Prisma.postWhereUniqueInput | Prisma.postWhereUniqueInput[]
}

export type postUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.postCreateWithoutUserInput, Prisma.postUncheckedCreateWithoutUserInput> | Prisma.postCreateWithoutUserInput[] | Prisma.postUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.postCreateOrConnectWithoutUserInput | Prisma.postCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.postUpsertWithWhereUniqueWithoutUserInput | Prisma.postUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.postCreateManyUserInputEnvelope
  set?: Prisma.postWhereUniqueInput | Prisma.postWhereUniqueInput[]
  disconnect?: Prisma.postWhereUniqueInput | Prisma.postWhereUniqueInput[]
  delete?: Prisma.postWhereUniqueInput | Prisma.postWhereUniqueInput[]
  connect?: Prisma.postWhereUniqueInput | Prisma.postWhereUniqueInput[]
  update?: Prisma.postUpdateWithWhereUniqueWithoutUserInput | Prisma.postUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.postUpdateManyWithWhereWithoutUserInput | Prisma.postUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.postScalarWhereInput | Prisma.postScalarWhereInput[]
}

export type postUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.postCreateWithoutUserInput, Prisma.postUncheckedCreateWithoutUserInput> | Prisma.postCreateWithoutUserInput[] | Prisma.postUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.postCreateOrConnectWithoutUserInput | Prisma.postCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.postUpsertWithWhereUniqueWithoutUserInput | Prisma.postUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.postCreateManyUserInputEnvelope
  set?: Prisma.postWhereUniqueInput | Prisma.postWhereUniqueInput[]
  disconnect?: Prisma.postWhereUniqueInput | Prisma.postWhereUniqueInput[]
  delete?: Prisma.postWhereUniqueInput | Prisma.postWhereUniqueInput[]
  connect?: Prisma.postWhereUniqueInput | Prisma.postWhereUniqueInput[]
  update?: Prisma.postUpdateWithWhereUniqueWithoutUserInput | Prisma.postUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.postUpdateManyWithWhereWithoutUserInput | Prisma.postUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.postScalarWhereInput | Prisma.postScalarWhereInput[]
}

export type postCreateWithoutUserInput = {
  id?: string
  title: string
  content: string
}

export type postUncheckedCreateWithoutUserInput = {
  id?: string
  title: string
  content: string
}

export type postCreateOrConnectWithoutUserInput = {
  where: Prisma.postWhereUniqueInput
  create: Prisma.XOR<Prisma.postCreateWithoutUserInput, Prisma.postUncheckedCreateWithoutUserInput>
}

export type postCreateManyUserInputEnvelope = {
  data: Prisma.postCreateManyUserInput | Prisma.postCreateManyUserInput[]
}

export type postUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.postWhereUniqueInput
  update: Prisma.XOR<Prisma.postUpdateWithoutUserInput, Prisma.postUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.postCreateWithoutUserInput, Prisma.postUncheckedCreateWithoutUserInput>
}

export type postUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.postWhereUniqueInput
  data: Prisma.XOR<Prisma.postUpdateWithoutUserInput, Prisma.postUncheckedUpdateWithoutUserInput>
}

export type postUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.postScalarWhereInput
  data: Prisma.XOR<Prisma.postUpdateManyMutationInput, Prisma.postUncheckedUpdateManyWithoutUserInput>
}

export type postScalarWhereInput = {
  AND?: Prisma.postScalarWhereInput | Prisma.postScalarWhereInput[]
  OR?: Prisma.postScalarWhereInput[]
  NOT?: Prisma.postScalarWhereInput | Prisma.postScalarWhereInput[]
  id?: Prisma.StringFilter<"post"> | string
  title?: Prisma.StringFilter<"post"> | string
  content?: Prisma.StringFilter<"post"> | string
  userId?: Prisma.StringFilter<"post"> | string
}

export type postCreateManyUserInput = {
  id?: string
  title: string
  content: string
}

export type postUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
}

export type postUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
}

export type postUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
}



export type postSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  content?: boolean
  userId?: boolean
  user?: boolean | Prisma.userDefaultArgs<ExtArgs>
}, ExtArgs["result"]["post"]>

export type postSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  content?: boolean
  userId?: boolean
  user?: boolean | Prisma.userDefaultArgs<ExtArgs>
}, ExtArgs["result"]["post"]>

export type postSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  content?: boolean
  userId?: boolean
  user?: boolean | Prisma.userDefaultArgs<ExtArgs>
}, ExtArgs["result"]["post"]>

export type postSelectScalar = {
  id?: boolean
  title?: boolean
  content?: boolean
  userId?: boolean
}

export type postOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "content" | "userId", ExtArgs["result"]["post"]>
export type postInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.userDefaultArgs<ExtArgs>
}
export type postIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.userDefaultArgs<ExtArgs>
}
export type postIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.userDefaultArgs<ExtArgs>
}

export type $postPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "post"
  objects: {
    user: Prisma.$userPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    content: string
    userId: string
  }, ExtArgs["result"]["post"]>
  composites: {}
}

export type postGetPayload<S extends boolean | null | undefined | postDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$postPayload, S>

export type postCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<postFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PostCountAggregateInputType | true
  }

export interface postDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['post'], meta: { name: 'post' } }
  /**
   * Find zero or one Post that matches the filter.
   * @param {postFindUniqueArgs} args - Arguments to find a Post
   * @example
   * // Get one Post
   * const post = await prisma.post.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends postFindUniqueArgs>(args: Prisma.SelectSubset<T, postFindUniqueArgs<ExtArgs>>): Prisma.Prisma__postClient<runtime.Types.Result.GetResult<Prisma.$postPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Post that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {postFindUniqueOrThrowArgs} args - Arguments to find a Post
   * @example
   * // Get one Post
   * const post = await prisma.post.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends postFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, postFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__postClient<runtime.Types.Result.GetResult<Prisma.$postPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Post that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {postFindFirstArgs} args - Arguments to find a Post
   * @example
   * // Get one Post
   * const post = await prisma.post.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends postFindFirstArgs>(args?: Prisma.SelectSubset<T, postFindFirstArgs<ExtArgs>>): Prisma.Prisma__postClient<runtime.Types.Result.GetResult<Prisma.$postPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Post that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {postFindFirstOrThrowArgs} args - Arguments to find a Post
   * @example
   * // Get one Post
   * const post = await prisma.post.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends postFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, postFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__postClient<runtime.Types.Result.GetResult<Prisma.$postPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Posts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {postFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Posts
   * const posts = await prisma.post.findMany()
   * 
   * // Get first 10 Posts
   * const posts = await prisma.post.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const postWithIdOnly = await prisma.post.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends postFindManyArgs>(args?: Prisma.SelectSubset<T, postFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$postPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Post.
   * @param {postCreateArgs} args - Arguments to create a Post.
   * @example
   * // Create one Post
   * const Post = await prisma.post.create({
   *   data: {
   *     // ... data to create a Post
   *   }
   * })
   * 
   */
  create<T extends postCreateArgs>(args: Prisma.SelectSubset<T, postCreateArgs<ExtArgs>>): Prisma.Prisma__postClient<runtime.Types.Result.GetResult<Prisma.$postPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Posts.
   * @param {postCreateManyArgs} args - Arguments to create many Posts.
   * @example
   * // Create many Posts
   * const post = await prisma.post.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends postCreateManyArgs>(args?: Prisma.SelectSubset<T, postCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Posts and returns the data saved in the database.
   * @param {postCreateManyAndReturnArgs} args - Arguments to create many Posts.
   * @example
   * // Create many Posts
   * const post = await prisma.post.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Posts and only return the `id`
   * const postWithIdOnly = await prisma.post.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends postCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, postCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$postPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Post.
   * @param {postDeleteArgs} args - Arguments to delete one Post.
   * @example
   * // Delete one Post
   * const Post = await prisma.post.delete({
   *   where: {
   *     // ... filter to delete one Post
   *   }
   * })
   * 
   */
  delete<T extends postDeleteArgs>(args: Prisma.SelectSubset<T, postDeleteArgs<ExtArgs>>): Prisma.Prisma__postClient<runtime.Types.Result.GetResult<Prisma.$postPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Post.
   * @param {postUpdateArgs} args - Arguments to update one Post.
   * @example
   * // Update one Post
   * const post = await prisma.post.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends postUpdateArgs>(args: Prisma.SelectSubset<T, postUpdateArgs<ExtArgs>>): Prisma.Prisma__postClient<runtime.Types.Result.GetResult<Prisma.$postPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Posts.
   * @param {postDeleteManyArgs} args - Arguments to filter Posts to delete.
   * @example
   * // Delete a few Posts
   * const { count } = await prisma.post.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends postDeleteManyArgs>(args?: Prisma.SelectSubset<T, postDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Posts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {postUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Posts
   * const post = await prisma.post.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends postUpdateManyArgs>(args: Prisma.SelectSubset<T, postUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Posts and returns the data updated in the database.
   * @param {postUpdateManyAndReturnArgs} args - Arguments to update many Posts.
   * @example
   * // Update many Posts
   * const post = await prisma.post.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Posts and only return the `id`
   * const postWithIdOnly = await prisma.post.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends postUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, postUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$postPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Post.
   * @param {postUpsertArgs} args - Arguments to update or create a Post.
   * @example
   * // Update or create a Post
   * const post = await prisma.post.upsert({
   *   create: {
   *     // ... data to create a Post
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Post we want to update
   *   }
   * })
   */
  upsert<T extends postUpsertArgs>(args: Prisma.SelectSubset<T, postUpsertArgs<ExtArgs>>): Prisma.Prisma__postClient<runtime.Types.Result.GetResult<Prisma.$postPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Posts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {postCountArgs} args - Arguments to filter Posts to count.
   * @example
   * // Count the number of Posts
   * const count = await prisma.post.count({
   *   where: {
   *     // ... the filter for the Posts we want to count
   *   }
   * })
  **/
  count<T extends postCountArgs>(
    args?: Prisma.Subset<T, postCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PostCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Post.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PostAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PostAggregateArgs>(args: Prisma.Subset<T, PostAggregateArgs>): Prisma.PrismaPromise<GetPostAggregateType<T>>

  /**
   * Group by Post.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {postGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends postGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: postGroupByArgs['orderBy'] }
      : { orderBy?: postGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, postGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPostGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the post model
 */
readonly fields: postFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for post.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__postClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.userDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.userDefaultArgs<ExtArgs>>): Prisma.Prisma__userClient<runtime.Types.Result.GetResult<Prisma.$userPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the post model
 */
export interface postFieldRefs {
  readonly id: Prisma.FieldRef<"post", 'String'>
  readonly title: Prisma.FieldRef<"post", 'String'>
  readonly content: Prisma.FieldRef<"post", 'String'>
  readonly userId: Prisma.FieldRef<"post", 'String'>
}
    

// Custom InputTypes
/**
 * post findUnique
 */
export type postFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the post
   */
  select?: Prisma.postSelect<ExtArgs> | null
  /**
   * Omit specific fields from the post
   */
  omit?: Prisma.postOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.postInclude<ExtArgs> | null
  /**
   * Filter, which post to fetch.
   */
  where: Prisma.postWhereUniqueInput
}

/**
 * post findUniqueOrThrow
 */
export type postFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the post
   */
  select?: Prisma.postSelect<ExtArgs> | null
  /**
   * Omit specific fields from the post
   */
  omit?: Prisma.postOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.postInclude<ExtArgs> | null
  /**
   * Filter, which post to fetch.
   */
  where: Prisma.postWhereUniqueInput
}

/**
 * post findFirst
 */
export type postFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the post
   */
  select?: Prisma.postSelect<ExtArgs> | null
  /**
   * Omit specific fields from the post
   */
  omit?: Prisma.postOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.postInclude<ExtArgs> | null
  /**
   * Filter, which post to fetch.
   */
  where?: Prisma.postWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of posts to fetch.
   */
  orderBy?: Prisma.postOrderByWithRelationInput | Prisma.postOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for posts.
   */
  cursor?: Prisma.postWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` posts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` posts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of posts.
   */
  distinct?: Prisma.PostScalarFieldEnum | Prisma.PostScalarFieldEnum[]
}

/**
 * post findFirstOrThrow
 */
export type postFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the post
   */
  select?: Prisma.postSelect<ExtArgs> | null
  /**
   * Omit specific fields from the post
   */
  omit?: Prisma.postOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.postInclude<ExtArgs> | null
  /**
   * Filter, which post to fetch.
   */
  where?: Prisma.postWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of posts to fetch.
   */
  orderBy?: Prisma.postOrderByWithRelationInput | Prisma.postOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for posts.
   */
  cursor?: Prisma.postWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` posts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` posts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of posts.
   */
  distinct?: Prisma.PostScalarFieldEnum | Prisma.PostScalarFieldEnum[]
}

/**
 * post findMany
 */
export type postFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the post
   */
  select?: Prisma.postSelect<ExtArgs> | null
  /**
   * Omit specific fields from the post
   */
  omit?: Prisma.postOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.postInclude<ExtArgs> | null
  /**
   * Filter, which posts to fetch.
   */
  where?: Prisma.postWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of posts to fetch.
   */
  orderBy?: Prisma.postOrderByWithRelationInput | Prisma.postOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing posts.
   */
  cursor?: Prisma.postWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` posts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` posts.
   */
  skip?: number
  distinct?: Prisma.PostScalarFieldEnum | Prisma.PostScalarFieldEnum[]
}

/**
 * post create
 */
export type postCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the post
   */
  select?: Prisma.postSelect<ExtArgs> | null
  /**
   * Omit specific fields from the post
   */
  omit?: Prisma.postOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.postInclude<ExtArgs> | null
  /**
   * The data needed to create a post.
   */
  data: Prisma.XOR<Prisma.postCreateInput, Prisma.postUncheckedCreateInput>
}

/**
 * post createMany
 */
export type postCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many posts.
   */
  data: Prisma.postCreateManyInput | Prisma.postCreateManyInput[]
}

/**
 * post createManyAndReturn
 */
export type postCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the post
   */
  select?: Prisma.postSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the post
   */
  omit?: Prisma.postOmit<ExtArgs> | null
  /**
   * The data used to create many posts.
   */
  data: Prisma.postCreateManyInput | Prisma.postCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.postIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * post update
 */
export type postUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the post
   */
  select?: Prisma.postSelect<ExtArgs> | null
  /**
   * Omit specific fields from the post
   */
  omit?: Prisma.postOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.postInclude<ExtArgs> | null
  /**
   * The data needed to update a post.
   */
  data: Prisma.XOR<Prisma.postUpdateInput, Prisma.postUncheckedUpdateInput>
  /**
   * Choose, which post to update.
   */
  where: Prisma.postWhereUniqueInput
}

/**
 * post updateMany
 */
export type postUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update posts.
   */
  data: Prisma.XOR<Prisma.postUpdateManyMutationInput, Prisma.postUncheckedUpdateManyInput>
  /**
   * Filter which posts to update
   */
  where?: Prisma.postWhereInput
  /**
   * Limit how many posts to update.
   */
  limit?: number
}

/**
 * post updateManyAndReturn
 */
export type postUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the post
   */
  select?: Prisma.postSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the post
   */
  omit?: Prisma.postOmit<ExtArgs> | null
  /**
   * The data used to update posts.
   */
  data: Prisma.XOR<Prisma.postUpdateManyMutationInput, Prisma.postUncheckedUpdateManyInput>
  /**
   * Filter which posts to update
   */
  where?: Prisma.postWhereInput
  /**
   * Limit how many posts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.postIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * post upsert
 */
export type postUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the post
   */
  select?: Prisma.postSelect<ExtArgs> | null
  /**
   * Omit specific fields from the post
   */
  omit?: Prisma.postOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.postInclude<ExtArgs> | null
  /**
   * The filter to search for the post to update in case it exists.
   */
  where: Prisma.postWhereUniqueInput
  /**
   * In case the post found by the `where` argument doesn't exist, create a new post with this data.
   */
  create: Prisma.XOR<Prisma.postCreateInput, Prisma.postUncheckedCreateInput>
  /**
   * In case the post was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.postUpdateInput, Prisma.postUncheckedUpdateInput>
}

/**
 * post delete
 */
export type postDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the post
   */
  select?: Prisma.postSelect<ExtArgs> | null
  /**
   * Omit specific fields from the post
   */
  omit?: Prisma.postOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.postInclude<ExtArgs> | null
  /**
   * Filter which post to delete.
   */
  where: Prisma.postWhereUniqueInput
}

/**
 * post deleteMany
 */
export type postDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which posts to delete
   */
  where?: Prisma.postWhereInput
  /**
   * Limit how many posts to delete.
   */
  limit?: number
}

/**
 * post without action
 */
export type postDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the post
   */
  select?: Prisma.postSelect<ExtArgs> | null
  /**
   * Omit specific fields from the post
   */
  omit?: Prisma.postOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.postInclude<ExtArgs> | null
}
